fit_path: data/fits/fit_minimal.npz
catalog_path: data/catalogs/essem_freq_kappa_catalog_22A_49G.json

tau_range_us: [0, 100]
tau_points: 600

selection_mode: top_kappa
num_spins: 1
distance_cutoff_A: 22.0
abundance_fraction: 0.011
reuse_present_mask: true

filters:
  contrast_min: 0.10
  t2_threshold_us: 2000.0
  keep_n: 15

seeds:
  site_seed: 4242
  fine_seed: 20251102

B_vec_G: [-41.57848995, -32.77145194, -27.5799348]
